=== UpperModel/JKPML/src/org/jkpml/xsd/gam/gam.system.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Document : system_schema.xsd Created on : September 29, 2003, 2:10 PM 
	Author : Ted Description: Purpose of XML Schema document follows. -->

<xs:schema xmlns="http://www.uppermodel.org/gam/systems"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uppermodel.org/gam/systems"
	elementFormDefault="qualified">
	<xs:element name="Region" type="RegionType" />
	<xs:complexType name="RegionType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="System" type="SystemType" />
			<xs:element name="Gate" type="GateType" />
		</xs:choice>
		<xs:attributeGroup ref="RegionAttributeGroup" />
	</xs:complexType>
	<xs:attributeGroup name="RegionAttributeGroup">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="stratum" type="stratumType" use="required" />
	</xs:attributeGroup>
	<xs:simpleType name="stratumType">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="Phonetics|Phonology|Graphics|Graphology|Lexicogrammar|Semantics" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SystemType">
		<xs:sequence>
			<xs:element name="EntryCondition" type="EntryConditionType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Feature" type="FeatureType" minOccurs="2" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attributeGroup ref="SystemAttributeGroup" />
	</xs:complexType>
	<xs:attributeGroup name="SystemAttributeGroup">
		<xs:attribute name="name" type="upper-case-string" use="required" />
		<xs:attribute name="metafunction" type="metafunctionType"
			default="None" />
	</xs:attributeGroup>
	<xs:complexType name="GateType">
		<xs:sequence>
			<xs:element name="EntryCondition" type="EntryConditionType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Feature" type="FeatureType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attributeGroup ref="GateAttributeGroup" />
	</xs:complexType>
	<xs:attributeGroup name="GateAttributeGroup">
		<xs:attribute name="name" type="upper-case-string" use="required" />
	</xs:attributeGroup>
	<xs:complexType name="EntryConditionType">
		<xs:choice minOccurs="1" maxOccurs="1">
			<xs:element name="And" type="AndType" />
			<xs:element name="Or" type="OrType" />
			<xs:element name="Not" type="NotType" />
			<xs:element name="Feature" type="FeatureIndexType" />
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="metafunctionType">
		<xs:restriction base="xs:string">
			<xs:pattern value="None|Ideational|Experiential|Logical|Interpersonal|Textual" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="FeatureType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Insert" type="InsertType" />
			<xs:element name="Expand" type="ExpandType" />
			<xs:element name="Conflate" type="ConflateType" />
			<xs:element name="PutAtFirst" type="PutAtFirstType" />
			<xs:element name="PutAtLast" type="PutAtLastType" />
			<xs:element name="PutAfter" type="PutAfterType" />
			<xs:element name="PutRightAfter" type="PutRightAfterType" />
			<xs:element name="Preselect" type="PreselectType" />
			<xs:element name="Classify" type="ClassifyType" />
			<xs:element name="Outclassify" type="OutclassifyType" />
			<xs:element name="Inflectify" type="InflectifyType" />
			<xs:element name="Lexify" type="LexifyType" />
			<xs:element name="Agree" type="AgreeType" />
		</xs:choice>
		<xs:attributeGroup ref="FeatureAttributeGroup" />
	</xs:complexType>
	<xs:attributeGroup name="FeatureAttributeGroup">
		<xs:attribute name="name" type="lower-case-string" use="required" />
		<xs:attribute name="active" type="xs:boolean" default="true" />
		<xs:attribute name="probability" type="xs:double"
			default="0.0" />
		<xs:attribute name="gloss" type="xs:string" default="" />
		<xs:attribute name="comment" type="xs:string" default="" />
	</xs:attributeGroup>
	<xs:attributeGroup name="TitleAttributeGroup">
		<xs:attribute name="a" type="title-case-string" use="required" />
	</xs:attributeGroup>
	<xs:attributeGroup name="TitleTitleAttributeGroup">
		<xs:attribute name="a" type="title-case-string" use="required" />
		<xs:attribute name="b" type="title-case-string" use="required" />
	</xs:attributeGroup>
	<xs:attributeGroup name="TitleLowerAttributeGroup">
		<xs:attribute name="a" type="title-case-string" use="required" />
		<xs:attribute name="b" type="lower-case-string" use="required" />
	</xs:attributeGroup>
	<xs:attributeGroup name="TitleUpperAttributeGroup">
		<xs:attribute name="a" type="title-case-string" use="required" />
		<xs:attribute name="b" type="upper-case-string" use="required" />
	</xs:attributeGroup>
	<xs:complexType name="InsertType">
		<xs:attributeGroup ref="TitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="ExpandType">
		<xs:attributeGroup ref="TitleTitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="ConflateType">
		<xs:attributeGroup ref="TitleTitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="PutAtFirstType">
		<xs:attributeGroup ref="TitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="PutAtLastType">
		<xs:attributeGroup ref="TitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="PutAfterType">
		<xs:attributeGroup ref="TitleTitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="PutRightAfterType">
		<xs:attributeGroup ref="TitleTitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="PreselectType">
		<xs:attributeGroup ref="TitleLowerAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="ClassifyType">
		<xs:attributeGroup ref="TitleLowerAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="OutclassifyType">
		<xs:attributeGroup ref="TitleLowerAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="InflectifyType">
		<xs:attributeGroup ref="TitleLowerAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="LexifyType">
		<xs:attributeGroup ref="TitleUpperAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="AgreeType">
		<xs:sequence>
			<xs:element name="Agreement" minOccurs="2" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Feature" type="FeatureIndexType"
							minOccurs="2" maxOccurs="2" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="TitleTitleAttributeGroup" />
	</xs:complexType>
	<xs:complexType name="FeatureIndexType">
		<xs:attribute name="name" type="lower-case-string" use="required" />
	</xs:complexType>
	<xs:complexType name="AndType">
		<xs:choice minOccurs="2" maxOccurs="unbounded">
			<xs:element name="And" type="AndType" />
			<xs:element name="Or" type="OrType" />
			<xs:element name="Not" type="NotType" />
			<xs:element name="Feature" type="FeatureIndexType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="OrType">
		<xs:choice minOccurs="2" maxOccurs="unbounded">
			<xs:element name="And" type="AndType" />
			<xs:element name="Or" type="OrType" />
			<xs:element name="Not" type="NotType" />
			<xs:element name="Feature" type="FeatureIndexType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="NotType">
		<xs:choice minOccurs="1" maxOccurs="1">
			<xs:element name="And" type="AndType" />
			<xs:element name="Or" type="OrType" />
			<xs:element name="Not" type="NotType" />
			<xs:element name="Feature" type="FeatureIndexType" />
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="title-case-string">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-z0-9]+(&amp;{0,1}[A-Z][a-z0-9]+)*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lower-case-string">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-z0-9]+([_&amp;-][a-z][a-z0-9]+)*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="upper-case-string">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][A-Z0-9]+([_&amp;-][A-Z][A-Z0-9]+)*" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== UpperModel/JKPML/src/org/jkpml/xsd/gam/gam.system.xml
<?xml version="1.0" encoding="UTF-8"?>

<Region xmlns="http://www.uppermodel.org/gam/systems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uppermodel.org/gam/systems gam.system.xsd"
	name="Sample" stratum="Lexicogrammar">
	<System name="STRATUM">
		<EntryCondition>
			<Feature name="structure" />
		</EntryCondition>
		<Feature name="semantic" />
		<Feature name="lexicogrammatical" />
		<Feature name="graphological" />
		<Feature name="graphical" />
		<Feature name="phonological" />
		<Feature name="phonetical" />
	</System>
	<System name="GRAMMATICAL-RANK">
		<EntryCondition>
			<Feature name="lexicogrammatical" />
		</EntryCondition>
		<Feature name="clause">
			<Insert a="Process" />
			<Conflate a="Process" b="Finite" />
			<Expand a="Mood" b="Finite" />
			<PutAtFirst a="Mood" />
			<PutAtLast a="Tag" />
			<PutRightAfter a="Subject" b="Finite" />
			<PutAfter a="Process" b="Attribute" />
			<Preselect a="Subject" b="nominative" />
			<Classify a="Process" b="verb" />
			<Outclassify a="Process" b="auxiliary-verb" />
			<Inflectify a="Process" b="present" />
			<Lexify a="Process" b="BEING-SOMEWHERE" />
			<Agree a="Subject" b="Process">
				<Agreement>
					<Feature name="addresser" />
					<Feature name="addresser-conjugated" />
				</Agreement>
				<Agreement>
					<Feature name="addressee" />
					<Feature name="addressee-conjugated" />
				</Agreement>
				<Agreement>
					<Feature name="non-concerned-singular" />
					<Feature name="non-concerned-singular-conjugated" />
				</Agreement>
				<Agreement>
					<Feature name="plural" />
					<Feature name="plural-conjugated" />
				</Agreement>
			</Agree>
		</Feature>
		<Feature name="mention" probability="0.5" />
		<Feature name="word" />
		<Feature name="morpheme" />
	</System>
</Region>

=== UpperModel/JKPML/TestResources/experiential-functions.system.gam.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Region xmlns="http://www.uppermodel.org/gam/systems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="experiential-functions" stratum="Lexicogrammar" xsi:schemaLocation="http://www.uppermodel.org/gam/systems gam.system.xsd">
    <System metafunction="Ideational" name="RELATIONAL-MODE">
        <EntryCondition>
            <Feature name="relational"/>
        </EntryCondition>
        <Feature name="attributive" probability="0.5">
            <Insert a="Carrier"/>
            <Insert a="Attribute"/>
        </Feature>
        <Feature name="identifying" probability="0.5">
            <Insert a="Token"/>
            <Insert a="Value"/>
        </Feature>
    </System>
    <System metafunction="Ideational" name="RELATIONAL">
        <EntryCondition>
            <Feature name="relational2"/>
        </EntryCondition>
        <Feature name="epithet" probability="0.3333333333333333"/>
        <Feature name="possessive2" probability="0.3333333333333333"/>
        <Feature name="incidental2" probability="0.3333333333333333"/>
    </System>
    <System metafunction="Ideational" name="RELATIONAL-TYPE2">
        <EntryCondition>
            <Feature name="relational-participant"/>
        </EntryCondition>
        <Feature name="carrier" probability="0.5"/>
        <Feature name="attribute" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="RELATIONAL-TYPE1">
        <EntryCondition>
            <Feature name="relational-participant"/>
        </EntryCondition>
        <Feature name="possessor" probability="0.14285714285714285"/>
        <Feature name="possessed" probability="0.14285714285714285"/>
        <Feature name="domain" probability="0.14285714285714285"/>
        <Feature name="range" probability="0.14285714285714285"/>
        <Feature name="incidence" probability="0.14285714285714285"/>
        <Feature name="entity" probability="0.14285714285714285"/>
        <Feature name="property" probability="0.14285714285714285"/>
    </System>
    <System metafunction="Ideational" name="CLAUSE-TYPE">
        <EntryCondition>
            <Feature name="clause"/>
        </EntryCondition>
        <Feature name="being-and-having" probability="0.5"/>
        <Feature name="doing-and-happening" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="EXPERITIAL-DOWNRANKED">
        <EntryCondition>
            <Feature name="downranked"/>
        </EntryCondition>
        <Feature name="relational2" probability="0.5"/>
        <Feature name="thing" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="RANK">
        <EntryCondition>
            <Feature name="wording"/>
        </EntryCondition>
        <Feature name="clause" probability="0.5"/>
        <Feature name="group-phrase" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="INTERPERSONAL-DOWNRANKED">
        <EntryCondition>
            <Feature name="downranked"/>
        </EntryCondition>
        <Feature name="head" probability="0.5"/>
        <Feature name="modifier" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="POSSESSIVE-DIATHESIS">
        <EntryCondition>
            <Feature name="possessive"/>
        </EntryCondition>
        <Feature name="having-type" probability="0.5"/>
        <Feature name="belonging-type" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="RELATIONAL-TYPE">
        <EntryCondition>
            <Feature name="relational"/>
        </EntryCondition>
        <Feature name="intrinsic" probability="0.3333333333333333"/>
        <Feature name="incidental" probability="0.3333333333333333"/>
        <Feature name="possessive" probability="0.3333333333333333">
            <Insert a="Possessor"/>
            <Insert a="Possessed"/>
        </Feature>
    </System>
    <System metafunction="Ideational" name="POSSESSIVE-TYPE">
        <EntryCondition>
            <Feature name="possessive"/>
        </EntryCondition>
        <Feature name="ownership&amp;belonging" probability="0.5"/>
        <Feature name="part&amp;part-of" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="INCIDENCE-TYPE">
        <EntryCondition>
            <Feature name="incidence"/>
        </EntryCondition>
        <Feature name="circumstance" probability="0.5"/>
        <Feature name="circumhabence" probability="0.5"/>
    </System>
    <System metafunction="Ideational" name="POSSESSIVE2-TYPE">
        <EntryCondition>
            <Feature name="possessive2"/>
        </EntryCondition>
        <Feature name="thing-with-parts" probability="0.25"/>
        <Feature name="part-of-thing" probability="0.25"/>
        <Feature name="belonging" probability="0.25"/>
        <Feature name="owner" probability="0.25"/>
    </System>
    <System metafunction="Ideational" name="EXPERIENTIAL-FUNCTION">
        <EntryCondition>
            <Feature name="group-phrase"/>
        </EntryCondition>
        <Feature name="process" probability="0.3333333333333333"/>
        <Feature name="relational-participant" probability="0.3333333333333333"/>
        <Feature name="downranked" probability="0.3333333333333333"/>
    </System>
    <System metafunction="Ideational" name="BEING-AND-HAVING-TYPE">
        <EntryCondition>
            <Feature name="being-and-having"/>
        </EntryCondition>
        <Feature name="relational" probability="0.5"/>
        <Feature name="existential" probability="0.5"/>
    </System>
    <Gate name="ATTRIBUTIVE-HAVING-TYPE-GATE">
        <EntryCondition>
            <And>
                <Feature name="having-type"/>
                <Feature name="attributive"/>
            </And>
        </EntryCondition>
        <Feature name="attributive-having-type">
            <Conflate a="Carrier" b="Possessor"/>
            <Conflate a="Attribute" b="Possessed"/>
        </Feature>
    </Gate>
    <Gate name="ATTRIBUTIVE-BELONGING-TYPE-GATE">
        <EntryCondition>
            <And>
                <Feature name="belonging-type"/>
                <Feature name="attributive"/>
            </And>
        </EntryCondition>
        <Feature name="attributive-belonging-type">
            <Conflate a="Carrier" b="Possessed"/>
            <Conflate a="Attribute" b="Possessor"/>
        </Feature>
    </Gate>
</Region>
