=== UpperModel/JKPML/TestResources/kpml.system.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : system_schema.xsd
    Created on : September 29, 2003, 2:10 PM
    Author     : Ted
    Description:
        Purpose of XML Schema document follows.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                      targetNamespace="http://www.fb10.uni-bremen.de/anglistik/langpro/kpml/README.html" 
                      xmlns="http://www.fb10.uni-bremen.de/anglistik/langpro/kpml/README.html" 
                      elementFormDefault="qualified">
    <!-- <xsd:include schemaLocation="system_output_schema"/> -->                   
    <xsd:element name="SYSTEMS">
        <xsd:complexType>  
            <xsd:sequence>
                <xsd:element name="COMMENTS" type="xsd:string">
                </xsd:element>
                <xsd:element name="IN-REGION" type="xsd:string">
                </xsd:element>
                <xsd:element name="IN-LANGUAGE">
                    <xsd:simpleType>
                        <xsd:list itemType="xsd:string"/>
                    </xsd:simpleType>
                </xsd:element>                
                <xsd:element name="SYSTEM" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="SYSTEM-TYPE">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="SYSTEM"/>
                                        <xsd:enumeration value="GATE"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="NAME" type="xsd:string"/>
                            <xsd:element name="INPUTS" type="booleanExpressionType"/>
                            <xsd:element name="OUTPUTS" type="outputExpressionType"/>
                            <xsd:element name="CHOOSER" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="REGION" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="METAFUNCTION" minOccurs="0">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="EXPERIENTIAL"/>
                                        <xsd:enumeration value="IDEATIONAL"/>
                                        <xsd:enumeration value="LOGICAL"/>
                                        <xsd:enumeration value="INTERPERSONAL"/>
                                        <xsd:enumeration value="TEXTUAL"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>    
        </xsd:complexType>
    </xsd:element>
    
    <!--FOLLOWING GIVES SPECIFICATION OF BOOLEAN-TYPES -->
    
    <xsd:complexType name="booleanExpressionType">
        <xsd:annotation><xsd:documentation>
        This complexType is a definition for boolean expressions,
        as used by the system specification files of KPML to satte
        what features are required as input .
        These contain orExpressions, andExpressions, and base symbols.
        </xsd:documentation></xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="s" type="logicSymbolType"/>
            <xsd:element name="and" type="andExpressionType"/>
            <xsd:element name="or" type="orExpressionType"/>
        </xsd:choice>
    </xsd:complexType>            
       
    <xsd:complexType name="orExpressionType">
        <xsd:choice minOccurs="2" maxOccurs="unbounded">
            <xsd:element name="s" type="logicSymbolType"/>
            <xsd:element name="and" type="andExpressionType"/>
            <xsd:element name="or" type="orExpressionType"/>
        </xsd:choice>
    </xsd:complexType>
   
    <xsd:complexType name="andExpressionType">
        <xsd:choice minOccurs="2" maxOccurs="unbounded">
            <xsd:element name="s" type="logicSymbolType"/>
            <xsd:element name="and" type="andExpressionType"/>
            <xsd:element name="or" type="orExpressionType"/>
        </xsd:choice>
    </xsd:complexType>
    
    <xsd:simpleType name="logicSymbolType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9a-zA-Z\-_]*"/>
        </xsd:restriction>
    </xsd:simpleType>    
        
       
    <!--FOLLOWING GIVES SPECIFICATION OF OUTPUT-TYPES -->
            <xsd:complexType name="outputExpressionType">
                <xsd:sequence>
                    <xsd:element name="out" minOccurs="1" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="probability" type="xsd:decimal"/>
                                <xsd:element name="feature" type="xsd:string"/>
                                <xsd:element name="realization" minOccurs="0" maxOccurs="1">
                                    <xsd:complexType>
                                        <xsd:choice minOccurs="1" maxOccurs="unbounded">
                                            <xsd:element name="insert" type="insertType"/>
                                            <xsd:element name="order-at-front" type="order-at-frontType"/>
                                            <xsd:element name="order-at-end" type="order-at-endType"/>
                                            <xsd:element name="expand" type="expandType"/>
                                            <xsd:element name="conflate" type="conflateType"/>
                                            <xsd:element name="preselect" type="preselectType"/>
                                            <xsd:element name="partition" type="partitionType"/>
                                            <xsd:element name="order" type="orderType"/>
                                            <xsd:element name="classify" type="classifyType"/>   
                                            <xsd:element name="outclassify" type="outclassifyType"/>
                                            <xsd:element name="inflectify" type="inflectifyType"/>
                                            <xsd:element name="lexify" type="lexifyType"/>
                                            <xsd:element name="agreement" type="agreementType"/>               
                                        </xsd:choice>
                                    </xsd:complexType>
                                </xsd:element>
                                <!--<xsd:element ref="realization" minOccurs="0" maxOccurs="unbounded"/>-->                                        
                            </xsd:sequence>      
                        </xsd:complexType>
                    </xsd:element>    
                </xsd:sequence>    
             </xsd:complexType> 
             
             <!--FOLLOWs GIVES SPECIFICATION OF REALIZATION OPERATORS,
                    THAT ARE EMBEDDED IN THE OUTPUT EXPRESSIONS-->
             
             <xsd:complexType name="insertType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="order-at-frontType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="order-at-endType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
            
             <xsd:complexType name="expandType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="conflateType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="preselectType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="partitionType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="orderType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="classifyType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="outclassifyType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="inflectifyType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
             
             <xsd:complexType name="lexifyType">
                <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>
                            <xsd:element name="b" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:extension>
                </xsd:complexContent>
             </xsd:complexType>
            
             <xsd:complexType name="agreementType">
                 <xsd:annotation><xsd:documentation>
                        An agreement realization statement has the most complex
                        syntax: it accepts a single string argument (the feature
                        to which the agreement is applied, followed by at least
                        one realization expression, which can be either one or
                        two argument functions.
                        ? can agreement accept another agreement as argument ?
                 </xsd:documentation></xsd:annotation>
                 <xsd:complexContent>
                    <xsd:extension base="realizationType" >
                        <xsd:sequence>
                            <xsd:element name="a" type="xsd:string"/>    
                            <xsd:element name="b"  type="xsd:string"/>
                            <xsd:element name="realization">
                                <xsd:complexType>
                                    <xsd:choice minOccurs="1" maxOccurs="unbounded">
                                        <xsd:element name="insert" type="insertType"/>
                                        <xsd:element name="order-at-front" type="order-at-frontType"/>
                                        <xsd:element name="order-at-end" type="order-at-endType"/>
                                        <xsd:element name="expand" type="expandType"/>
                                        <xsd:element name="conflate" type="conflateType"/>
                                        <xsd:element name="preselect" type="preselectType"/>
                                        <xsd:element name="partition" type="partitionType"/>
                                        <xsd:element name="order" type="orderType"/>
                                        <xsd:element name="classify" type="classifyType"/>   
                                        <xsd:element name="outclassify" type="outclassifyType"/>
                                        <xsd:element name="inflectify" type="inflectifyType"/>
                                        <xsd:element name="lexify" type="lexifyType"/>
                                        <xsd:element name="agreement" type="agreementType"/>               
                                    </xsd:choice>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:extension>
                 </xsd:complexContent>    
             </xsd:complexType>           
             
             <xsd:complexType name="realizationType" abstract="true">
                <xsd:sequence>        
                </xsd:sequence>
             </xsd:complexType>
</xsd:schema>

=== UpperModel/JKPML/TestResources/experiential-functions.system.kpml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SYSTEMS xmlns="http://www.fb10.uni-bremen.de/anglistik/langpro/kpml/README.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fb10.uni-bremen.de/anglistik/langpro/kpml/README.html kpml.system.xsd">
    <COMMENTS/>
    <IN-REGION>experiential-functions</IN-REGION>
    <IN-LANGUAGE/>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RELATIONAL-MODE</NAME>
        <INPUTS>
            <s>relational</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>attributive</feature>
                <realization>
                    <insert>
                        <a>Carrier</a>
                    </insert>
                    <insert>
                        <a>Attribute</a>
                    </insert>
                </realization>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>identifying</feature>
                <realization>
                    <insert>
                        <a>Token</a>
                    </insert>
                    <insert>
                        <a>Value</a>
                    </insert>
                </realization>
            </out>
        </OUTPUTS>
        <CHOOSER>RELATIONAL-MODE-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RELATIONAL</NAME>
        <INPUTS>
            <s>relational2</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>epithet</feature>
            </out>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>possessive2</feature>
            </out>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>incidental2</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>RELATIONAL-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RELATIONAL-TYPE2</NAME>
        <INPUTS>
            <s>relational-participant</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>carrier</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>attribute</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>RELATIONAL-TYPE2-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RELATIONAL-TYPE1</NAME>
        <INPUTS>
            <s>relational-participant</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>possessor</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>possessed</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>domain</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>range</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>incidence</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>entity</feature>
            </out>
            <out>
                <probability>0.14285714285714285</probability>
                <feature>property</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>RELATIONAL-TYPE1-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>CLAUSE-TYPE</NAME>
        <INPUTS>
            <s>clause</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>being-and-having</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>doing-and-happening</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>CLAUSE-TYPE-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>EXPERITIAL-DOWNRANKED</NAME>
        <INPUTS>
            <s>downranked</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>relational2</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>thing</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>EXPERITIAL-DOWNRANKED-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RANK</NAME>
        <INPUTS>
            <s>wording</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>clause</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>group-phrase</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>RANK-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>INTERPERSONAL-DOWNRANKED</NAME>
        <INPUTS>
            <s>downranked</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>head</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>modifier</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>INTERPERSONAL-DOWNRANKED-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>POSSESSIVE-DIATHESIS</NAME>
        <INPUTS>
            <s>possessive</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>having-type</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>belonging-type</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>POSSESSIVE-DIATHESIS-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>RELATIONAL-TYPE</NAME>
        <INPUTS>
            <s>relational</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>intrinsic</feature>
            </out>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>incidental</feature>
            </out>
            <out>
                <probability>0.3333333333333333</probability>
                <feature>possessive</feature>
                <realization>
                    <insert>
                        <a>Possessor</a>
                    </insert>
                    <insert>
                        <a>Possessed</a>
                    </insert>
                </realization>
            </out>
        </OUTPUTS>
        <CHOOSER>RELATIONAL-TYPE-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>POSSESSIVE-TYPE</NAME>
        <INPUTS>
            <s>possessive</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>ownership&amp;belonging</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>part&amp;part-of</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>POSSESSIVE-TYPE-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>INCIDENCE-TYPE</NAME>
        <INPUTS>
            <s>incidence</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.5</probability>
                <feature>circumstance</feature>
            </out>
            <out>
                <probability>0.5</probability>
                <feature>circumhabence</feature>
            </out>
        </OUTPUTS>
        <CHOOSER>INCIDENCE-TYPE-CHOOSER</CHOOSER>
        <REGION>experiential-functions</REGION>
        <METAFUNCTION>IDEATIONAL</METAFUNCTION>
    </SYSTEM>
    <SYSTEM>
        <SYSTEM-TYPE>SYSTEM</SYSTEM-TYPE>
        <NAME>POSSESSIVE2-TYPE</NAME>
        <INPUTS>
            <s>possessive2</s>
        </INPUTS>
        <OUTPUTS>
            <out>
                <probability>0.25</probability>
                <feature>thing-with-parts</feature>
            </out>
