=== UpperModel/JKPML/TestResources/uam.system.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Document : system_schema.xsd Created on : September 29, 2003, 2:10 PM 
	Author : Ted Description: Purpose of XML Schema document follows. -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uppermodel.org/uam/systems" xmlns="http://www.uppermodel.org/uam/systems"
	elementFormDefault="qualified">
	<!-- <xsd:include schemaLocation="system_output_schema"/> -->
	<xsd:element name="NETWORK">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ROOT">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="FEATURE" type="featureIndexType" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="SYSTEMS">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SYSTEM" minOccurs="1" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="NAME" type="xsd:string" />
										<xsd:element name="EC" type="ecType" minOccurs="1"
											maxOccurs="1" />
										<xsd:element name="FEATURES" type="featureType" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="featureIndexType">
		<xsd:sequence>
			<xsd:element name="NAME" type="xsd:string" />
			<xsd:element name="STATE" type="stateType" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="stateType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="active|inactive" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="ecType" mixed="true">
		<xsd:sequence>
			<xsd:element name="OP" minOccurs="0" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="and|or|not" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="FEATURE" type="featureIndexType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<!--FOLLOWING GIVES SPECIFICATION OF BOOLEAN-TYPES -->

	<xsd:complexType name="booleanExpressionType">
		<xsd:annotation>
			<xsd:documentation>
				This complexType is a definition for boolean
				expressions,
				as used by the system specification files of KPML to
				satte
				what features are required as input .
				These contain
				orExpressions, andExpressions, and base symbols.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="s" type="logicSymbolType" />
			<xsd:element name="and" type="andExpressionType" />
			<xsd:element name="or" type="orExpressionType" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="orExpressionType">
		<xsd:choice minOccurs="2" maxOccurs="unbounded">
			<xsd:element name="s" type="logicSymbolType" />
			<xsd:element name="and" type="andExpressionType" />
			<xsd:element name="or" type="orExpressionType" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="andExpressionType">
		<xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="logicSymbolType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9a-zA-Z\-_]*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="featureType">
		<xsd:sequence>
			<xsd:element name="FEATURE" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="NAME" type="xsd:string" />
						<xsd:element name="STATE" type="stateType" />
						<xsd:element name="REALISATIONS" minOccurs="0"
							maxOccurs="1">
							<xsd:complexType>
								<xsd:choice minOccurs="1" maxOccurs="unbounded">
									<xsd:element name="REALISATION" type="realisationType" />
								</xsd:choice>
							</xsd:complexType>
						</xsd:element>
						<!--<xsd:element ref="realization" minOccurs="0" maxOccurs="unbounded"/> -->
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="realisationType">
		<xsd:sequence>
			<xsd:element name="OP" type="opType" />
			<xsd:element name="ARGS" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="opType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern
				value="Insert|Conflate|Expand|PutAtFirst|PutAtLast|PutBefore|PutRightBefore|PutAfter|PutRightAfter|Preselect|Classify|Outclassify|Inflectify|Lexify|Agree" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== UpperModel/JKPML/TestResources/experiential-functions.system.uam.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<NETWORK xmlns="http://www.uppermodel.org/uam/systems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uppermodel.org/uam/systems uam.system.xsd">
    <ROOT>
        <FEATURE>
            <NAME>wording</NAME>
            <STATE>active</STATE>
        </FEATURE>
    </ROOT>
    <SYSTEMS>
        <SYSTEM>
            <NAME>RELATIONAL-MODE</NAME>
            <EC>relational</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>attributive</NAME>
                    <STATE>active</STATE>
                    <REALISATIONS>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Carrier</ARGS>
                        </REALISATION>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Attribute</ARGS>
                        </REALISATION>
                    </REALISATIONS>
                </FEATURE>
                <FEATURE>
                    <NAME>identifying</NAME>
                    <STATE>active</STATE>
                    <REALISATIONS>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Token</ARGS>
                        </REALISATION>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Value</ARGS>
                        </REALISATION>
                    </REALISATIONS>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>RELATIONAL</NAME>
            <EC>relational2</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>epithet</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>possessive2</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>incidental2</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>RELATIONAL-TYPE2</NAME>
            <EC>relational-participant</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>carrier</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>attribute</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>RELATIONAL-TYPE1</NAME>
            <EC>relational-participant</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>possessor</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>possessed</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>domain</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>range</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>incidence</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>entity</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>property</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>CLAUSE-TYPE</NAME>
            <EC>clause</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>being-and-having</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>doing-and-happening</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>EXPERITIAL-DOWNRANKED</NAME>
            <EC>downranked</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>relational2</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>thing</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>RANK</NAME>
            <EC>wording</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>clause</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>group-phrase</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>INTERPERSONAL-DOWNRANKED</NAME>
            <EC>downranked</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>head</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>modifier</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>POSSESSIVE-DIATHESIS</NAME>
            <EC>possessive</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>having-type</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>belonging-type</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>RELATIONAL-TYPE</NAME>
            <EC>relational</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>intrinsic</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>incidental</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>possessive</NAME>
                    <STATE>active</STATE>
                    <REALISATIONS>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Possessor</ARGS>
                        </REALISATION>
                        <REALISATION>
                            <OP>Insert</OP>
                            <ARGS>Possessed</ARGS>
                        </REALISATION>
                    </REALISATIONS>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>POSSESSIVE-TYPE</NAME>
            <EC>possessive</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>ownership&amp;belonging</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>part&amp;part-of</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>INCIDENCE-TYPE</NAME>
            <EC>incidence</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>circumstance</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>circumhabence</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>POSSESSIVE2-TYPE</NAME>
            <EC>possessive2</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>thing-with-parts</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>part-of-thing</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>belonging</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>owner</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>EXPERIENTIAL-FUNCTION</NAME>
            <EC>group-phrase</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>process</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>relational-participant</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>downranked</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>BEING-AND-HAVING-TYPE</NAME>
            <EC>being-and-having</EC>
            <FEATURES>
                <FEATURE>
                    <NAME>relational</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>existential</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </FEATURES>
        </SYSTEM>
        <SYSTEM>
            <NAME>ATTRIBUTIVE-HAVING-TYPE-GATE</NAME>
            <EC>
                <OP>and</OP>
                <FEATURE>
                    <NAME>having-type</NAME>
                    <STATE>active</STATE>
                </FEATURE>
                <FEATURE>
                    <NAME>attributive</NAME>
                    <STATE>active</STATE>
                </FEATURE>
            </EC>
            <FEATURES>
